on:
  release:
    types: [published]

name: Release Build and Push
permissions:
    contents: read
    id-token: write

env:
  IMAGE: system-agent-installer-k3s
  REPO: rancher

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
          include:
            - arch: amd64
              os: linux
            - arch: arm64
              os: linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set environment variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "OS=${{ matrix.os }}"     >> "$GITHUB_ENV"

      - name: Download installer
        run: scripts/download

      - name: Publish Image - Docker
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}
          make-target: push-image

          public-repo: ${{ env.REPO }}
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          push-to-prime: false

  create-docker-manifest:
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          . scripts/version

      - name: Publish Manifest - Docker
        uses: rancher/ecm-distro-tools/actions/publish-image@master
        with:
          image: ${{ env.IMAGE }}
          tag: ${{ github.ref_name }}
          make-target: publish-manifest

          public-repo: ${{ env.REPO }}
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          push-to-prime: false

      - name: Inspect Docker image
        run: docker buildx imagetools inspect ${{ env.REPO }}/${{ env.IMAGE }}:${{ env.VERSION }}
